### ISSUE TITLE
Reading and displaying bibtex files on an overview page for Publication

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/bexis2.github.io#13]
- [ ] Collect all publications on the Publications page into one folder
- [ ] Reading the bibtext files
- [ ] Display of the publication as a citation string

**Comment by DavidBlaa** [comment]
currently there was a problem reading bibtex files from a folder.

1. solution check this post
https://github.com/vitejs/vite/issues/5478

2. solution 
put all publications in one file and read it out

**Comment by gdeioannes** [comment]
Will work in the previous solution

**Comment by gdeioannes** [comment]
Still need permission to push the feature and merge with the Master

**Comment by geofranzi** [comment]
I added you to the repo

**Comment by geofranzi** [comment]
Please commit to a new own branch. We will merge it, as we need to ensure it does not break the page.

**Comment by geofranzi** [comment]
not anymore planned
